version: '3'
services:
  db:
    image: postgres:14.2-alpine
    env_file: ./docker-env/.env.pg
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build:
      context: .
      target: dev-build
    env_file: ./docker-env/.env
    command: >
      sh -c "rm -f tmp/pids/server.pid &&
      bundle exec rails server -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
