version: '3'
services:
  db:
    image: postgres:14.2-alpine
    env_file: ./docker-env/.env.pg
    volumes:
      # point to your postgres init scripts (folder or file)
      - ./docker-entrypoints/db_init:/entrypoint-initdb.d
      # if you need persistent data, point data to local folder
      - ./tmp/db:/var/lib/postgresql/data
      # point docker to directory with your config
      - ./docker-files/db_config:/db_config
  api:
    build:
      context: .
      target: dev-build
    env_file: ./docker-env/.env
    command: >
      sh -c "rm -f tmp/pids/server.pid &&
      bundle exec rails server -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    tty: true
    stdin_open: true
  redis:
    image: 'redis:7.0-rc-alpine'
    env_file: ./docker-env/.env
    command: sh -c "redis-server"
    ports:
      - '6379:6379'
    volumes:
      - '.:/var/lib/redis/data'
  sidekiq:
    build: .
    env_file: ./docker-env/.env
    command: sh -c "bundle exec sidekiq"
    volumes:
      - '.:/myapp'
    depends_on:
      - 'db'
      - 'redis'
    tty: true
    stdin_open: true
